###register request

Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "Roya.frn1",
    "email" : "roya1@gmail.com",
    "mobile" : "09173621511",
    "password" : "12345671",
    "confirm_password" : "12345671"
}


###Login request

Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username" : "Roya.frn3",
    "password" : "12345678"
}