### get user profile
get http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}

### edit user profile
Post http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "first_name" : "roya3",
    "last_name" : "frn3",
    "skills" : ["programming","nest.js","node.js"]
}